// <auto-generated />
namespace Task_Management_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class detailedTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(detailedTask));
        
        string IMigrationMetadata.Id
        {
            get { return "202207261425400_detailedTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
