// <auto-generated />
namespace Task_Management_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class detailedTask1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(detailedTask1));
        
        string IMigrationMetadata.Id
        {
            get { return "202207261428267_detailedTask1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
